export const deportes = [
  { id: 'running', nombre: 'Correr', icono: '🏃', tipo: 'run' },
  { id: 'senderismo', nombre: 'Senderismo', icono: '🥾', tipo: 'run' },
  { id: 'ciclismo', nombre: 'Ciclismo', icono: '🚴', tipo: 'bike' },
  { id: 'natacion', nombre: 'Natación', icono: '🏊', tipo: 'swim' },
  { id: 'futbol', nombre: 'Fútbol', icono: '⚽', tipo: 'sport' },
  { id: 'baloncesto', nombre: 'Baloncesto', icono: '🏀', tipo: 'sport' },
  { id: 'tenis', nombre: 'Tenis', icono: '🎾', tipo: 'sport' },
  { id: 'voleibol', nombre: 'Voleibol', icono: '🏐', tipo: 'sport' },
  { id: 'boxeo', nombre: 'Boxeo', icono: '🥊', tipo: 'strength' },
  { id: 'gimnasia', nombre: 'Gimnasia', icono: '🤸', tipo: 'strength' },
  { id: 'yoga', nombre: 'Yoga', icono: '🧘', tipo: 'strength' },
  { id: 'halterofilia', nombre: 'Halterofilia', icono: '🏋️', tipo: 'strength' },
  { id: 'artes_marciales', nombre: 'Artes marciales', icono: '🥋', tipo: 'strength' },
  { id: 'esqui', nombre: 'Esquí', icono: '⛷️', tipo: 'sport' },
  { id: 'surf', nombre: 'Surf', icono: '🏄', tipo: 'sport' },
  { id: 'remo', nombre: 'Remo', icono: '🚣', tipo: 'sport' },
  { id: 'patinaje', nombre: 'Patinaje', icono: '🛼', tipo: 'sport' },
  { id: 'triatlon', nombre: 'Triatlón', icono: '🏅', tipo: 'sport' },
]