export const traduccionesDeportes = {
  'Soccer': 'Fútbol',
  'Swimming': 'Natación',
  'Cycling': 'Ciclismo',
  'Running': 'Atletismo',
  'Basketball': 'Baloncesto',
  'Baseball': 'Béisbol',
  'Tennis': 'Tenis',
  'Golf': 'Golf',
  'Volleyball': 'Voleibol',
  'Boxing': 'Boxeo',
  'MMA': 'Artes marciales mixtas',
  'Motorsport': 'Automovilismo',
  'Rugby': 'Rugby',
  'Cricket': 'Críquet',
  'Hockey': 'Hockey',
  'American Football': 'Fútbol americano',
  'Gymnastics': 'Gimnasia',
  'Skiing': 'Esquí',
  'Snowboarding': 'Snowboard',
  'Surfing': 'Surf',
  'Darts': 'Dardos',
  'Table Tennis': 'Tenis de mesa',
  'Badminton': 'Bádminton',
  'Handball': 'Balonmano',
  'Weightlifting': 'Halterofilia',
  'Climbing': 'Escalada',
  'Skateboarding': 'Patineta',
  'Rowing': 'Remo',
  'Sailing': 'Vela',
  'Equestrian': 'Equitación',
  'Fencing': 'Esgrima',
  'Triathlon': 'Triatlón',
  'Archery': 'Tiro con arco',
}

export function traducirDeporte(nombreIngles) {
  return traduccionesDeportes[nombreIngles] || nombreIngles
}